'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '../../..');
const html = fs.readFileSync(path.join(__dirname, '../../../packages/drawer-app/index.html'), 'utf8');
const css = fs.readFileSync(path.join(__dirname, '../../../packages/drawer-app/css/03-diagram.css'), 'utf8');
const shell = fs.readFileSync(path.join(__dirname, '../../../packages/drawer-app/js/01-shell-state.js'), 'utf8');
const boot = fs.readFileSync(path.join(__dirname, '../../../packages/drawer-app/js/07-chrome-boot.js'), 'utf8');
const board = fs.readFileSync(path.join(root, 'skill/board/SKILL.md'), 'utf8');
const viewer = fs.readFileSync(path.join(root, 'skill/board/references/viewer.md'), 'utf8');
const vocab = fs.readFileSync(path.join(root, 'skill/board/references/vocab.md'), 'utf8');
const themes = fs.readFileSync(path.join(root, 'packages/board/themes/index.js'), 'utf8');

assert.ok(/id="btnSourceCopyId"/.test(html), 'Source has Copy ID');
assert.ok(!/id="sourceDockId"/.test(html), 'Source title does not print the record ID');
assert.ok(!/\.dock-source-id\s*\{/.test(css), 'no live ID chip style');
assert.ok(/title="Copy ID"[^>]*>ID</.test(html), 'Source button says ID');
assert.ok(/title="Copy Source"[^>]*>Source</.test(html), 'Source button says Source');
assert.ok(/<button[^>]*id="btnSourceCopyId"[^>]*>/.test(html) && /<button[^>]*class="btn"[^>]*id="btnSourceCopyId"/.test(html) && !/id="btnSourceCopyId"[^>]*ghost/.test(html), 'Copy ID is a bordered button');
assert.ok(/<button[^>]*class="btn"[^>]*id="btnSourceCopy"[^>]*>/.test(html) && !/<button[^>]*id="btnSourceCopy"[^>]*ghost/.test(html), 'Copy Source is a bordered button');
assert.ok(!/id="snapPill"/.test(html) && !/id="boardSnapPill"/.test(html), 'no record snap pills');
assert.ok(/id="boardDockResize"/.test(html), 'sidebar has a resize handle');
assert.ok(/class="source-chars"/.test(html), 'chars sit on the editor');
assert.ok(/class="props-field"/.test(html) && /id="boardDirEditor"[\s\S]*id="boardDirTip"/.test(html), 'property tips sit under the control');
assert.ok(/flex-direction:\s*row/.test(css) && /\.dock-source-head\s*\{/.test(css), 'Source head is a row');
assert.ok(/--dock-open-width/.test(css), 'open sidebar width is a variable');
assert.ok(/function applyDockWidth/.test(shell), 'sidebar width is applied');
assert.ok(/dockWidth/.test(shell), 'sidebar width is persisted');
assert.ok(!/Copy BMD ID|Copy MMD ID/.test(html + shell + boot), 'visible copy labels drop BMD/MMD');
assert.ok(/function syncSourceIdChrome/.test(shell), 'ID chrome syncs with live meta');
assert.ok(/btnSourceCopyId/.test(boot), 'Copy ID is wired');
assert.ok(!fs.existsSync(path.join(root, 'skill/SKILL.md')), 'no pack SKILL at skill root');
assert.ok(/\*\*BMD ID\*\*/.test(board) && /\*\*BMD Source\*\*/.test(board), 'board SKILL defines BMD terms');
assert.ok(/Keep `id` \(BMD ID\) first/.test(board), 'board flow keeps BMD ID first');
assert.ok(/`--id` is BMD ID/.test(viewer), 'viewer names BMD ID');
assert.ok(/Required on\s+`get-source`/.test(viewer), 'viewer requires --id on get-source');
assert.ok(!/mermaid:\s*'default'/.test(themes), 'theme map drops mermaid alias');
assert.ok(/They are not the Drawer BMD ID/.test(vocab), 'vocab node IDs are not BMD ID');
assert.ok(/meta <base64>/.test(vocab), 'vocab names the meta envelope');
assert.ok(!/id="syncPill"/.test(html), 'Source does not show a rev pill');
assert.ok(!/id="boardSyncPill"/.test(html), 'Board Source does not show a rev pill');
assert.ok(/liveDocumentVersion/.test(shell), 'Source title reads document version');
assert.ok(/id="sourceDockVersion"/.test(html) && /function formatVersionLabel/.test(shell), 'version sits beside the type name');
assert.ok(/title.textContent = "Board"/.test(shell), 'Source title is Board');
assert.ok(/function setCharsLabel/.test(shell), 'chars use a formatted count');
assert.ok(shell.includes("if (!/^\\s*meta\\s+/.test(text))"), 'API wrap only peels meta envelopes');
assert.ok(/var doc = splitDocument\(text\)/.test(shell), 'API wrap still splits a meta document');
assert.ok(/document meta required/.test(fs.readFileSync(path.join(__dirname, '../../../skill/scripts/document_meta.py'), 'utf8')), 'hard-cut lives in document_meta');

console.log('ok bmd-id-first');
